### ISSUE TITLE
GitHub Stars (and link) point to DataLad

### ISSUE THREAD

**Issue by dnkennedy** [ReproNim/HowWouldReproNim#22]
On the overview page: https://how-would.repronim.org/en/latest/index.html
in the left sidebar, under the ReproNim logo is a GitHub link and star counter display.

The link and star counter are for the DataLad handbook (https://github.com/datalad-handbook/book) which is nice, but probably not what we want. I presume that this should be the stars and link to https://github.com/ReproNim/HowWouldReproNim

I would have tried to fix this if I could have figures out where in hack that framing code lives...

This issue also exists in the left sidebbar of Volume 1 (and maybe other volumes, I've not checked yet).

**Comment by adswa** [comment]
Whoopsie, my bad. :) Will fix in a minute

**Comment by adswa** [comment]
> I would have tried to fix this if I could have figures out where in hack that framing code lives...

I found it by running ``git grep handbook``:

```
git grep handbook
_static/custom.css:44: * TODOs should not be a frequent feature in the handbook */
_templates/sidebarintro.html:7:<p style="margin-left:auto; margin-right: auto;"><iframe src="https://ghbtns.com/github-btn.html?repo=book&user=datalad-handbook&type=star&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="200px" height="35px"></iframe></p>
_templates/sidebarlogo.html:7:<p style="margin-left:auto; margin-right: auto;"><iframe src="https://ghbtns.com/github-btn.html?repo=book&user=datalad-handbook&type=star&count=true&size=large" allowtransparency="true" frameborder="0" scrolling="0" width="200px" height="35px"></iframe></p>
vol01/localcontainer.rst:603:- DataLad: `Documentation <http://handbook.datalad.org/en/latest/>`_, `ReproNim Training <http://www.repronim.org/module-reproducible-basics/02-vcs/#datalad>`_
vol02/publishdata.rst:182:infrastructure” <http://handbook.datalad.org/en/latest/basics/basics8toc.html>`__).
vol02/publishdata.rst:898:-  DataLad: `Documentation <http://handbook.datalad.org/en/latest/>`__,
vol09/containerizeworkflow.rst:1021:`here <http://handbook.datalad.org/en/latest/>`__. We will discuss this
```
