### ISSUE TITLE
Import existing volumes

### ISSUE THREAD

**Issue by chaselgrove** [ReproNim/HowWouldReproNim#6]
- [x] Volume 1: [How would ReproNim do a Local Container Analysis?](https://docs.google.com/document/d/1Mq8Tsn8o8EKz2O4dyJJaHdNtZTzptb9eoGcZk7ZfsnE/edit#heading=h.f2r73p8wqece)
- [x] Volume 2: [How Would ReproNim Publish a Dataset?](https://docs.google.com/document/d/1wv-COdc2wYHepTENGZ8PbcWuxWLMjxMmvKPxOdJhkRY/edit#heading=h.f2r73p8wqece)
- [x] Volume 4: [How Would ReproNim Manage Local FreeSurfer Results?](https://docs.google.com/document/d/18Ud5RWec-As65-FFgkzcwf9agVtxW9bcozZeuLyfRNM/edit#heading=h.f2r73p8wqece)
- [x] Volume 6: [How Would ReproNim Do an Analysis on ABCD Data?
](https://docs.google.com/document/d/1KR_dU3FMu2Fa67SZqMu_FnUWJID5qnRwyfGfni7k9Uw/edit#heading=h.6xrv3m2migir)
- [x] Volume 9: [How Would ReproNim Containerize a Workflow?](https://docs.google.com/document/d/1J93-tOpKtXQvOZ_fD0-8JV4W5iSBrXbIF6UVEpm37_8/edit#heading=h.f2r73p8wqece)

**Comment by chaselgrove** [comment]
@adswa how did you convert Volume 1 to RST?  Are there tools to assist, or did you do it all by hand?

**Comment by adswa** [comment]
Apologies, this notification slipped through. I have indeed done it by hand, but [pandoc](https://pandoc.org/demos.html) should be able to do .docx to .rst conversions, IIRC.
